/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgentVisualizer.java
 *
 * Created on 11.06.2009, 15:49:42
 */

package de.hu_berlin.informatik.ki.jxabsleditor.graphpanel;

/**
 *
 * @author thomas
 */
public class AgentVisualizer extends javax.swing.JPanel {

    /** Creates new form AgentVisualizer */
    public AgentVisualizer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();

    setLayout(new java.awt.BorderLayout());

    jLabel1.setText("not implemented yet");
    add(jLabel1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables

}
