/*
 * Copyright 2009 NaoTeam Humboldt
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.naoth.xabsleditor;

import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Enumeration;
import java.util.Properties;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.KeyStroke;

/**
 *
 * @author Heinrich Mellmann
 */
public class OptionsDialog extends javax.swing.JDialog
{

  public static final String DEFAULT_COMPILATION_PATH = "defaultCompilationPath";
  public static final String XABSL_COMPILER_COMMAND = "xabslCompilerCommand";
  public static final String USE_INSTALLED_RUBY = "useInstalledRuby";
  public static final String OPEN_LAST_AGENT = "openLastAgent";
  public static final String START_POSITION = "startPosition";
  public static final String[] START_POSITION_OPTIONS = { "default", "last", "maximized" };
  public static final String[] START_POSITION_VALUE = { "startPositionX", "startPositionY", "startPositionWidth", "startPositionHeight" };

  public static final String EDITOR_TAB_SIZE = "editorTabSize";
  public static final String EDITOR_TAB_CLOSE_BTN = "editorTabCloseButton";
  
  private Properties configuration;

  /** Creates new form Options */
  public OptionsDialog(java.awt.Frame parent, boolean modal, Properties configuration)
  {
    super(parent, modal);
    initComponents();
    
    // close preference/options dialog with esc key!
    this.getRootPane().registerKeyboardAction(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCancelActionPerformed(evt);
        }
    }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);

    this.configuration = configuration;
    loadOptions();
  }

  private void loadOptions()
  {

    if(configuration.containsKey(DEFAULT_COMPILATION_PATH))
    {
      this.txtDefaultCompilationPath.setText(configuration.getProperty(DEFAULT_COMPILATION_PATH));
    }

    if(configuration.containsKey(XABSL_COMPILER_COMMAND))
    {
      this.txtXabslCompilerCommand.setText(configuration.getProperty(XABSL_COMPILER_COMMAND));
    }

    if(configuration.containsKey(USE_INSTALLED_RUBY))
    {
      if(Boolean.parseBoolean(configuration.getProperty(USE_INSTALLED_RUBY)) == Boolean.TRUE)
        this.cbUseRuby.setSelected(true);
      else
        this.cbUseRuby.setSelected(false);
    }

    if(configuration.containsKey(EDITOR_TAB_SIZE))
    {
      int n = Integer.parseInt(configuration.getProperty(EDITOR_TAB_SIZE));
      this.spTabSize.setValue(n);
    }
    
    this.cbTabCloseBtn.setSelected(Boolean.parseBoolean(configuration.getProperty(EDITOR_TAB_CLOSE_BTN)));
    this.cbOpenLastAgent.setSelected(Boolean.parseBoolean(configuration.getProperty(OPEN_LAST_AGENT)));
    //
    
    String startPosition = configuration.getProperty(START_POSITION, "");
    Enumeration<AbstractButton> items = this.bgStartBehavior.getElements();
    while(items.hasMoreElements()){
        AbstractButton btn = items.nextElement();
        if(startPosition.equals(btn.getActionCommand())) {
            this.bgStartBehavior.setSelected(btn.getModel(), true);
        }
    }
      //System.out.println(this.bgStartBehavior.getSelection());
//    /this.cbStartMaximized.setSelected(Boolean.parseBoolean(configuration.getProperty(START_MAXIMIZED)));
  }//end loadOptions

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserCompilationPath = new javax.swing.JFileChooser();
        bgStartBehavior = new javax.swing.ButtonGroup();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        optionPanel = new javax.swing.JTabbedPane();
        jpCompiler = new javax.swing.JPanel();
        cbUseRuby = new javax.swing.JCheckBox();
        txtDefaultCompilationPath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtXabslCompilerCommand = new javax.swing.JTextField();
        btBrowseCompilation = new javax.swing.JButton();
        jpEditor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spTabSize = new javax.swing.JSpinner();
        cbTabCloseBtn = new javax.swing.JCheckBox();
        cbOpenLastAgent = new javax.swing.JCheckBox();
        jpStartBehavior = new javax.swing.JPanel();
        startPosition_default = new javax.swing.JRadioButton();
        startPosition_last = new javax.swing.JRadioButton();
        startPosition_maximized = new javax.swing.JRadioButton();

        fileChooserCompilationPath.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        setModal(true);
        setName("Preferences"); // NOI18N
        setResizable(false);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        cbUseRuby.setSelected(true);
        cbUseRuby.setText("try to use installed ruby");

        jLabel2.setText("Default compilation path");

        jLabel3.setText("XABSL Compiler command");

        btBrowseCompilation.setText("Browse...");
        btBrowseCompilation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrowseCompilationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCompilerLayout = new javax.swing.GroupLayout(jpCompiler);
        jpCompiler.setLayout(jpCompilerLayout);
        jpCompilerLayout.setHorizontalGroup(
            jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompilerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompilerLayout.createSequentialGroup()
                        .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtDefaultCompilationPath, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBrowseCompilation))
                    .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtXabslCompilerCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(cbUseRuby)))
                .addGap(20, 20, 20))
        );
        jpCompilerLayout.setVerticalGroup(
            jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompilerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefaultCompilationPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBrowseCompilation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXabslCompilerCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbUseRuby)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPanel.addTab("Compiler", jpCompiler);

        jLabel4.setText("Tab Size");

        spTabSize.setModel(new javax.swing.SpinnerNumberModel(2, 0, 13, 1));

        cbTabCloseBtn.setText("Show close button");
        cbTabCloseBtn.setToolTipText("Whether or not the close button for an editor tab should be shown.");
        cbTabCloseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        cbOpenLastAgent.setText("Open last agent on start");
        cbOpenLastAgent.setToolTipText("Always opens the last agent, when program starts.");
        cbOpenLastAgent.setActionCommand("lastAgent");
        cbOpenLastAgent.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jpStartBehavior.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Positioning on startup"));
        jpStartBehavior.setLayout(new javax.swing.BoxLayout(jpStartBehavior, javax.swing.BoxLayout.Y_AXIS));

        bgStartBehavior.add(startPosition_default);
        startPosition_default.setSelected(true);
        startPosition_default.setText("Default");
        startPosition_default.setActionCommand(START_POSITION_OPTIONS[0]);
        jpStartBehavior.add(startPosition_default);

        bgStartBehavior.add(startPosition_last);
        startPosition_last.setText("Remember last position & size");
        startPosition_last.setActionCommand(START_POSITION_OPTIONS[1]);
        jpStartBehavior.add(startPosition_last);

        bgStartBehavior.add(startPosition_maximized);
        startPosition_maximized.setText("Start maximized");
        startPosition_maximized.setActionCommand(START_POSITION_OPTIONS[2]);
        jpStartBehavior.add(startPosition_maximized);

        javax.swing.GroupLayout jpEditorLayout = new javax.swing.GroupLayout(jpEditor);
        jpEditor.setLayout(jpEditorLayout);
        jpEditorLayout.setHorizontalGroup(
            jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spTabSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTabCloseBtn)
                    .addComponent(cbOpenLastAgent))
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addComponent(jpStartBehavior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpEditorLayout.setVerticalGroup(
            jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spTabSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTabCloseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbOpenLastAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpStartBehavior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        optionPanel.addTab("Editor", jpEditor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

      // save settings
      if("".equals(txtDefaultCompilationPath.getText()) && configuration.containsKey(DEFAULT_COMPILATION_PATH))
      {
        configuration.remove(DEFAULT_COMPILATION_PATH);
      }
      else
      {
        configuration.setProperty(DEFAULT_COMPILATION_PATH, txtDefaultCompilationPath.getText());
      }

      if("".equals(txtXabslCompilerCommand.getText()) && configuration.containsKey(XABSL_COMPILER_COMMAND))
      {
        configuration.remove(XABSL_COMPILER_COMMAND);
      }
      else
      {
        configuration.setProperty(XABSL_COMPILER_COMMAND,
          txtXabslCompilerCommand.getText());
      }

      configuration.setProperty(USE_INSTALLED_RUBY, Boolean.toString(this.cbUseRuby.isSelected()));
      
      configuration.setProperty(OPEN_LAST_AGENT, Boolean.toString(this.cbOpenLastAgent.isSelected()));

      configuration.setProperty(EDITOR_TAB_SIZE, this.spTabSize.getValue().toString());
      configuration.setProperty(EDITOR_TAB_CLOSE_BTN, Boolean.toString(this.cbTabCloseBtn.isSelected()));

      configuration.setProperty(START_POSITION, this.bgStartBehavior.getSelection().getActionCommand());
      
      this.setVisible(false);
      this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void btBrowseCompilationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btBrowseCompilationActionPerformed
    {//GEN-HEADEREND:event_btBrowseCompilationActionPerformed

      File fPath = new File(System.getProperty("user.dir"));
      if(!"".equals(txtDefaultCompilationPath.getText()))
      {
        fPath = new File(txtDefaultCompilationPath.getText());
        
      }

      fileChooserCompilationPath.setSelectedFile(fPath);
      if(fileChooserCompilationPath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
      {
        txtDefaultCompilationPath.setText(fileChooserCompilationPath.getSelectedFile().getAbsolutePath());
      }

}//GEN-LAST:event_btBrowseCompilationActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
      this.setVisible(false);
      this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgStartBehavior;
    private javax.swing.JButton btBrowseCompilation;
    private javax.swing.JCheckBox cbOpenLastAgent;
    private javax.swing.JCheckBox cbTabCloseBtn;
    private javax.swing.JCheckBox cbUseRuby;
    private javax.swing.JFileChooser fileChooserCompilationPath;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpCompiler;
    private javax.swing.JPanel jpEditor;
    private javax.swing.JPanel jpStartBehavior;
    private javax.swing.JTabbedPane optionPanel;
    private javax.swing.JSpinner spTabSize;
    private javax.swing.JRadioButton startPosition_default;
    private javax.swing.JRadioButton startPosition_last;
    private javax.swing.JRadioButton startPosition_maximized;
    private javax.swing.JTextField txtDefaultCompilationPath;
    private javax.swing.JTextField txtXabslCompilerCommand;
    // End of variables declaration//GEN-END:variables
}
