/*
 * Copyright 2009 NaoTeam Humboldt
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.naoth.xabsleditor;

import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Properties;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.KeyStroke;

/**
 *
 * @author Heinrich Mellmann
 */
public class OptionsDialog extends javax.swing.JDialog
{

  public static final String DEFAULT_COMPILATION_PATH = "defaultCompilationPath";
  public static final String XABSL_COMPILER_COMMAND = "xabslCompilerCommand";
  public static final String USE_INSTALLED_RUBY = "useInstalledRuby";

  public static final String EDITOR_TAB_SIZE = "editorTabSize";
  
  private Properties configuration;

  /** Creates new form Options */
  public OptionsDialog(java.awt.Frame parent, boolean modal, Properties configuration)
  {
    super(parent, modal);
    initComponents();
    
    // close preference/options dialog with esc key!
    this.getRootPane().registerKeyboardAction(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCancelActionPerformed(evt);
        }
    }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);

    this.configuration = configuration;
    loadOptions();
  }

  private void loadOptions()
  {

    if(configuration.containsKey(DEFAULT_COMPILATION_PATH))
    {
      this.txtDefaultCompilationPath.setText(configuration.getProperty(DEFAULT_COMPILATION_PATH));
    }

    if(configuration.containsKey(XABSL_COMPILER_COMMAND))
    {
      this.txtXabslCompilerCommand.setText(configuration.getProperty(XABSL_COMPILER_COMMAND));
    }

    if(configuration.containsKey(USE_INSTALLED_RUBY))
    {
      if(Boolean.parseBoolean(configuration.getProperty(USE_INSTALLED_RUBY)) == Boolean.TRUE)
        this.cbUseRuby.setSelected(true);
      else
        this.cbUseRuby.setSelected(false);
    }

    if(configuration.containsKey(EDITOR_TAB_SIZE))
    {
      int n = Integer.parseInt(configuration.getProperty(EDITOR_TAB_SIZE));
      this.spTabSize.setValue(n);
    }
  }//end loadOptions

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserCompilationPath = new javax.swing.JFileChooser();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        optionPanel = new javax.swing.JTabbedPane();
        jpCompiler = new javax.swing.JPanel();
        cbUseRuby = new javax.swing.JCheckBox();
        txtDefaultCompilationPath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtXabslCompilerCommand = new javax.swing.JTextField();
        btBrowseCompilation = new javax.swing.JButton();
        jpEditor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spTabSize = new javax.swing.JSpinner();

        fileChooserCompilationPath.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        setLocationByPlatform(true);
        setModal(true);
        setName("Preferences"); // NOI18N
        setResizable(false);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        cbUseRuby.setSelected(true);
        cbUseRuby.setText("try to use installed ruby");

        jLabel2.setText("Default compilation path");

        jLabel3.setText("XABSL Compiler command");

        btBrowseCompilation.setText("Browse...");
        btBrowseCompilation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrowseCompilationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCompilerLayout = new javax.swing.GroupLayout(jpCompiler);
        jpCompiler.setLayout(jpCompilerLayout);
        jpCompilerLayout.setHorizontalGroup(
            jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompilerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompilerLayout.createSequentialGroup()
                        .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtDefaultCompilationPath, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBrowseCompilation))
                    .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtXabslCompilerCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                        .addGroup(jpCompilerLayout.createSequentialGroup()
                            .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(cbUseRuby))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGap(20, 20, 20))
        );
        jpCompilerLayout.setVerticalGroup(
            jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompilerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCompilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefaultCompilationPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBrowseCompilation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXabslCompilerCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbUseRuby)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPanel.addTab("Compiler", jpCompiler);

        jLabel4.setText("Tab Size");

        spTabSize.setModel(new javax.swing.SpinnerNumberModel(2, 0, 13, 1));

        javax.swing.GroupLayout jpEditorLayout = new javax.swing.GroupLayout(jpEditor);
        jpEditor.setLayout(jpEditorLayout);
        jpEditorLayout.setHorizontalGroup(
            jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTabSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jpEditorLayout.setVerticalGroup(
            jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spTabSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        optionPanel.addTab("Editor", jpEditor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

      // save settings
      if("".equals(txtDefaultCompilationPath.getText()) && configuration.containsKey(DEFAULT_COMPILATION_PATH))
      {
        configuration.remove(DEFAULT_COMPILATION_PATH);
      }
      else
      {
        configuration.setProperty(DEFAULT_COMPILATION_PATH, txtDefaultCompilationPath.getText());
      }

      if("".equals(txtXabslCompilerCommand.getText()) && configuration.containsKey(XABSL_COMPILER_COMMAND))
      {
        configuration.remove(XABSL_COMPILER_COMMAND);
      }
      else
      {
        configuration.setProperty(XABSL_COMPILER_COMMAND,
          txtXabslCompilerCommand.getText());
      }

      configuration.setProperty(USE_INSTALLED_RUBY, Boolean.toString(this.cbUseRuby.isSelected()));


      configuration.setProperty(EDITOR_TAB_SIZE, this.spTabSize.getValue().toString());

      this.setVisible(false);
      this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void btBrowseCompilationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btBrowseCompilationActionPerformed
    {//GEN-HEADEREND:event_btBrowseCompilationActionPerformed

      File fPath = new File(System.getProperty("user.dir"));
      if(!"".equals(txtDefaultCompilationPath.getText()))
      {
        fPath = new File(txtDefaultCompilationPath.getText());
        
      }

      fileChooserCompilationPath.setSelectedFile(fPath);
      if(fileChooserCompilationPath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
      {
        txtDefaultCompilationPath.setText(fileChooserCompilationPath.getSelectedFile().getAbsolutePath());
      }

}//GEN-LAST:event_btBrowseCompilationActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
      this.setVisible(false);
      this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBrowseCompilation;
    private javax.swing.JCheckBox cbUseRuby;
    private javax.swing.JFileChooser fileChooserCompilationPath;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpCompiler;
    private javax.swing.JPanel jpEditor;
    private javax.swing.JTabbedPane optionPanel;
    private javax.swing.JSpinner spTabSize;
    private javax.swing.JTextField txtDefaultCompilationPath;
    private javax.swing.JTextField txtXabslCompilerCommand;
    // End of variables declaration//GEN-END:variables
}
