/*
 * Copyright 2009 NaoTeam Humboldt
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.hu_berlin.informatik.ki.jxabsleditor.editorpanel;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author thomas
 */
public class SearchPanel extends javax.swing.JPanel
{

  private XEditorPanel parent;
  
  public SearchPanel()
  {
    this(null);
  }

  /** Creates new form SearchPanel */
  public SearchPanel(XEditorPanel parent)
  {
    this.parent = parent;
    
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtSearch = new javax.swing.JTextField();

    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });

    jLabel1.setText("Search:");

    txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txtSearchKeyPressed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(1, 1, 1)
        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel1)
        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtSearchKeyPressed
  {//GEN-HEADEREND:event_txtSearchKeyPressed

    if(parent == null)
    {
      return;
    }
    if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
    {
      this.setVisible(false);
    }
    else if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
      if(parent.search(txtSearch.getText()))
      {
        txtSearch.setBackground(Color.white);
        txtSearch.setForeground(Color.black);
      }
      else
      {
        txtSearch.setBackground(Color.red);
        txtSearch.setForeground(Color.white);
      }
      txtSearch.grabFocus();
    }

  }//GEN-LAST:event_txtSearchKeyPressed

  private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
  {//GEN-HEADEREND:event_formComponentShown

    txtSearch.grabFocus();

  }//GEN-LAST:event_formComponentShown

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField txtSearch;
  // End of variables declaration//GEN-END:variables
}
